#!/usr/bin/env python
# coding: utf-8

# In[ ]:


# vendor_mapping.py
# -----------------------------------------------------------------------------------
# This file contains the vendor_groups mapping for Smart Transaction Categorization
# in the Finory AI Module. It maps vendor names to generalized category groups.
# -----------------------------------------------------------------------------------

vendor_groups = {
    '3M': 'Manufacturing / Industrial',
    'AbbVie': 'Healthcare',
    'Abbott Laboratories': 'Healthcare',
    'Accenture': 'Technology',
    'Activision Blizzard': 'Entertainment & Media',
    'Adobe Systems': 'Technology',
    'Advanced Micro Devices': 'Technology',
    'Aflac': 'Finance & Insurance',
    'Agilent Technologies': 'Healthcare',
    'Air Products & Chemicals': 'Manufacturing / Industrial',
    'Alaska Air Group': 'Travel & Transport',
    'Albemarle Corporation': 'Manufacturing / Industrial',
    'Alexion Pharmaceuticals': 'Healthcare',
    'Align Technology': 'Healthcare',
    'Allegion': 'Manufacturing / Industrial',
    'Alliant Energy': 'Energy & Utilities',
    'Allstate': 'Finance & Insurance',
    'Alphabet': 'Technology',
    'Altria Group': 'Retail',
    'Amazon': 'Retail',
    'Ameren': 'Energy & Utilities',
    'American Airlines Group': 'Travel & Transport',
    'American Electric Power': 'Energy & Utilities',
    'American Express': 'Finance & Insurance',
    'American International Group': 'Finance & Insurance',
    'American Tower': 'Real Estate',
    'American Water Works': 'Energy & Utilities',
    'Ameriprise Financial': 'Finance & Insurance',
    'AmerisourceBergen': 'Healthcare',
    'Ametek': 'Manufacturing / Industrial',
    'Amgen': 'Healthcare',
    'Amphenol': 'Manufacturing / Industrial',
    'Analog Devices': 'Technology',
    'Ansys': 'Technology',
    'Aon': 'Finance & Insurance',
    'APA Corporation': 'Energy & Utilities',
    'Apple': 'Technology',
    'Applied Materials': 'Technology',
    'Archer-Daniels-Midland': 'Retail',
    'Arista Networks': 'Technology',
    'Arthur J. Gallagher & Co.': 'Finance & Insurance',
    'Assurant': 'Finance & Insurance',
    'AT&T': 'Technology',
    'Atmos Energy': 'Energy & Utilities',
    'Autodesk': 'Technology',
    'Automatic Data Processing': 'Technology',
    'AutoZone': 'Retail',
    'AvalonBay Communities': 'Real Estate',
    'Avery Dennison': 'Manufacturing / Industrial',
    'Baker Hughes': 'Energy & Utilities',
    'Ball Corporation': 'Manufacturing / Industrial',
    'Bank of America': 'Finance & Insurance',
    'Bath & Body Works': 'Retail',
    'Baxter International': 'Healthcare',
    'Becton Dickinson': 'Healthcare',
    'Berkshire Hathaway': 'Finance & Insurance',
    'Best Buy': 'Retail',
    'Bio-Rad Laboratories': 'Healthcare',
    'Bio-Techne': 'Healthcare',
    'Biogen': 'Healthcare',
    'BlackRock': 'Finance & Insurance',
    'Boeing': 'Travel & Transport',
    'Booking Holdings': 'Travel & Transport',
    'BorgWarner': 'Manufacturing / Industrial',
    'Boston Properties': 'Real Estate',
    'Boston Scientific': 'Healthcare',
    'Bristol-Myers Squibb': 'Healthcare',
    'Broadcom': 'Technology',
    'Broadridge Financial Solutions': 'Finance & Insurance',
    'Brown & Brown': 'Finance & Insurance',
    'Brown-Forman': 'Retail',
    'C.H. Robinson Worldwide': 'Travel & Transport',
    'Cadence Design Systems': 'Technology',
    'Caesars Entertainment': 'Entertainment & Media',
    'Camden Property Trust': 'Real Estate',
    'Campbell Soup Company': 'Retail',
    'Capital One Financial': 'Finance & Insurance',
    'Cardinal Health': 'Healthcare',
    'CarMax': 'Retail',
    'Carnival Corporation': 'Travel & Transport',
    'Carrier Global': 'Manufacturing / Industrial',
    'Catalent': 'Healthcare',
    'Caterpillar': 'Manufacturing / Industrial',
    'Cboe Global Markets': 'Finance & Insurance',
    'CBRE Group': 'Real Estate',
    'CDW': 'Technology',
    'Celanese': 'Manufacturing / Industrial',
    'Centene Corporation': 'Healthcare',
    'CenterPoint Energy': 'Energy & Utilities',
    'Cerner': 'Healthcare',
    'CF Industries': 'Manufacturing / Industrial',
    'Charles River Laboratories': 'Healthcare',
    'Charles Schwab Corporation': 'Finance & Insurance',
    'Charter Communications': 'Technology',
    'Chevron Corporation': 'Energy & Utilities',
    'Chipotle Mexican Grill': 'Retail',
    'Chubb Limited': 'Finance & Insurance',
    'Church & Dwight': 'Retail',
    'Cigna': 'Healthcare',
    'Cincinnati Financial': 'Finance & Insurance',
    'Cintas': 'Manufacturing / Industrial',
    'Cisco Systems': 'Technology',
    'Citigroup': 'Finance & Insurance',
    'Citizens Financial Group': 'Finance & Insurance',
    'Clorox': 'Retail',
    'CME Group': 'Finance & Insurance',
    'CMS Energy': 'Energy & Utilities',
    'Coca-Cola Company': 'Retail',
    'Cognizant Technology Solutions': 'Technology',
    'Colgate-Palmolive': 'Retail',
    'Comcast': 'Technology',
    'Comerica': 'Finance & Insurance',
    'Conagra Brands': 'Retail',
    'ConocoPhillips': 'Energy & Utilities',
    'Consolidated Edison': 'Energy & Utilities',
    'Constellation Brands': 'Retail',
    'CooperCompanies': 'Healthcare',
    'Copart': 'Retail',
    'Corning Inc.': 'Manufacturing / Industrial',
    'Corteva': 'Manufacturing / Industrial',
    'Costco': 'Retail',
    'Coterra Energy': 'Energy & Utilities',
    'Crown Castle': 'Technology',
    'CSX': 'Travel & Transport',
    'Cummins': 'Manufacturing / Industrial',
    'CVS Health': 'Healthcare',
    'D.R. Horton': 'Real Estate',
    'Danaher Corporation': 'Healthcare',
    'Darden Restaurants': 'Retail',
    'DaVita Inc.': 'Healthcare',
    'Deere & Company': 'Hardware',
    'Delta Air Lines': 'Travel & Transport',
    'Dentsply Sirona': 'Healthcare',
    'Devon Energy': 'Energy & Utilities',
    'DexCom': 'Healthcare',
    'Diamondback Energy': 'Energy & Utilities',
    'Digital Realty': 'Real Estate',
    'Discover Financial Services': 'Finance & Insurance',
    'Dish Network': 'Technology',
    'Dollar General': 'Retail',
    'Dollar Tree': 'Retail',
    'Dominion Energy': 'Energy & Utilities',
    'Domino\'s Pizza': 'Retail',
    'Dover Corporation': 'Manufacturing / Industrial',
    'Dow Inc.': 'Manufacturing / Industrial',
    'DTE Energy': 'Energy & Utilities',
    'Duke Energy': 'Energy & Utilities',
    'DuPont': 'Manufacturing / Industrial',
    'DXC Technology': 'Technology',
    'Eastman Chemical Company': 'Manufacturing / Industrial',
    'Eaton Corporation': 'Manufacturing / Industrial',
    'eBay': 'Retail',
    'Ecolab': 'Manufacturing / Industrial',
    'Edison International': 'Energy & Utilities',
    'Edwards Lifesciences': 'Healthcare',
    'Electronic Arts': 'Entertainment & Media',
    'Elevance Health': 'Healthcare',
    'Eli Lilly and Company': 'Healthcare',
    'Emerson Electric': 'Manufacturing / Industrial',
    'Enphase Energy': 'Energy & Utilities',
    'Entergy': 'Energy & Utilities',
    'EOG Resources': 'Energy & Utilities',
    'EPAM Systems': 'Technology',
    'Equifax': 'Finance & Insurance',
    'Equinix': 'Real Estate',
    'Equity Residential': 'Real Estate',
    'Essex Property Trust': 'Real Estate',
    'Estee Lauder Companies': 'Retail',
    'Eversource Energy': 'Energy & Utilities',
    'Evergy': 'Energy & Utilities',
    'Everest Re': 'Finance & Insurance',
    'Exelon': 'Energy & Utilities',
    'Expedia Group': 'Travel & Transport',
    'Expeditors International': 'Travel & Transport',
    'Extra Space Storage': 'Real Estate',
    'ExxonMobil': 'Energy & Utilities',
    'F5 Networks': 'Technology',
    'FactSet': 'Technology',
    'Fastenal': 'Retail',
    'Federal Realty': 'Real Estate',
    'FedEx': 'Travel & Transport',
    'Fidelity National Information Services': 'Finance & Insurance',
    'Fifth Third Bancorp': 'Finance & Insurance',
    'First Republic Bank': 'Finance & Insurance',
    'First Solar': 'Energy & Utilities',
    'FirstEnergy': 'Energy & Utilities',
    'Fiserv': 'Finance & Insurance',
    'FleetCor': 'Finance & Insurance',
    'FMC Corporation': 'Manufacturing / Industrial',
    'Ford Motor Company': 'Travel & Transport',
    'Fortinet': 'Technology',
    'Fortive': 'Manufacturing / Industrial',
    'Fox Corporation': 'Entertainment & Media',
    'Franklin Resources': 'Finance & Insurance',
    'Freeport-McMoRan': 'Manufacturing / Industrial',
    'Garmin': 'Technology',
    'Gartner': 'Technology',
    'Generac': 'Manufacturing / Industrial',
    'General Dynamics': 'Manufacturing / Industrial',
    'General Electric': 'Manufacturing / Industrial',
    'General Mills': 'Retail',
    'General Motors': 'Travel & Transport',
    'Genuine Parts Company': 'Retail',
    'Gilead Sciences': 'Healthcare',
    'Globe Life': 'Finance & Insurance',
    'Global Payments': 'Finance & Insurance',
    'Goldman Sachs': 'Finance & Insurance',
    'Halliburton': 'Energy & Utilities',
    'Hartford Financial Services': 'Finance & Insurance',
    'Hasbro': 'Entertainment & Media',
    'HCA Healthcare': 'Healthcare',
    'Healthpeak Properties': 'Real Estate',
    'Henry Schein': 'Healthcare',
    'Hershey Company': 'Retail',
    'Hess Corporation': 'Energy & Utilities',
    'Hewlett Packard Enterprise': 'Technology',
    'Hilton Worldwide': 'Travel & Transport',
    'Hologic': 'Healthcare',
    'Home Depot': 'Retail',
    'Honeywell': 'Manufacturing / Industrial',
    'Hormel Foods': 'Retail',
    'Host Hotels & Resorts': 'Real Estate',
    'Howmet Aerospace': 'Manufacturing / Industrial',
    'HP Inc.': 'Technology',
    'Humana': 'Healthcare',
    'Huntington Bancshares': 'Finance & Insurance',
    'Huntington Ingalls Industries': 'Manufacturing / Industrial',
    'IDEX Corporation': 'Manufacturing / Industrial',
    'IDEXX Laboratories': 'Healthcare',
    'Illinois Tool Works': 'Manufacturing / Industrial',
    'Illumina': 'Healthcare',
    'Incyte': 'Healthcare',
    'Ingersoll Rand': 'Manufacturing / Industrial',
    'Intel': 'Technology',
    'Intercontinental Exchange': 'Finance & Insurance',
    'International Business Machines': 'Technology',
    'International Paper': 'Manufacturing / Industrial',
    'Interpublic Group': 'Marketing',
    'Intuit': 'Technology',
    'Intuitive Surgical': 'Healthcare',
    'Invesco': 'Finance & Insurance',
    'Invitation Homes': 'Real Estate',
    'IQVIA': 'Healthcare',
    'Iron Mountain': 'Real Estate',
    'J.B. Hunt Transport Services': 'Travel & Transport',
    'Jack Henry & Associates': 'Technology',
    'Jacobs Engineering': 'Manufacturing / Industrial',
    'Johnson & Johnson': 'Healthcare',
    'Johnson Controls': 'Manufacturing / Industrial',
    'JPMorgan Chase': 'Finance & Insurance',
    'Juniper Networks': 'Technology',
    'Kaiser Aluminum': 'Manufacturing / Industrial',
    'Kansas City Southern': 'Travel & Transport',
    'Kellogg Company': 'Retail',
    'KeyCorp': 'Finance & Insurance',
    'Keysight Technologies': 'Technology',
    'Kimberly-Clark': 'Retail',
    'Kimco Realty': 'Real Estate',
    'Kinder Morgan': 'Energy & Utilities',
    'KLA Corporation': 'Technology',
    'Kraft Heinz': 'Retail',
    'Kroger': 'Retail',
    'L3Harris Technologies': 'Technology',
    'Laboratory Corporation of America': 'Healthcare',
    'Lam Research': 'Technology',
    'Lamb Weston Holdings': 'Retail',
    'Las Vegas Sands': 'Entertainment & Media',
    'Leidos': 'Technology',
    'Lennar': 'Real Estate',
    'Lincoln National Corporation': 'Finance & Insurance',
    'Linde plc': 'Manufacturing / Industrial',
    'Live Nation Entertainment': 'Entertainment & Media',
    'LKQ Corporation': 'Retail',
    'Lockheed Martin': 'Manufacturing / Industrial',
    'Loews Corporation': 'Finance & Insurance',
    'Lowe\'s': 'Retail',
    'Lumen Technologies': 'Technology',
    'LyondellBasell': 'Manufacturing / Industrial',
    'M&T Bank': 'Finance & Insurance',
    'Marathon Oil': 'Energy & Utilities',
    'Marathon Petroleum': 'Energy & Utilities',
    'MarketAxess': 'Finance & Insurance',
    'Marriott International': 'Travel & Transport',
    'Marsh & McLennan': 'Finance & Insurance',
    'Martin Marietta Materials': 'Manufacturing / Industrial',
    'Masco': 'Manufacturing / Industrial',
    'Mastercard': 'Finance & Insurance',
    'Match Group': 'Entertainment & Media',
    'McCormick & Company': 'Retail',
    'McDonald\'s': 'Retail',
    'McKesson': 'Healthcare',
    'Medtronic': 'Healthcare',
    'Merck & Co.': 'Healthcare',
    'Meta Platforms': 'Technology',
    'MetLife': 'Finance & Insurance',
    'Mettler-Toledo': 'Healthcare',
    'MGM Resorts': 'Entertainment & Media',
    'Microchip Technology': 'Technology',
    'Micron Technology': 'Technology',
    'Microsoft': 'Technology',
    'Mid-America Apartment Communities': 'Real Estate',
    'Mohawk Industries': 'Manufacturing / Industrial',
    'Molson Coors Beverage Company': 'Retail',
    'Mondelez International': 'Retail',
    'Monolithic Power Systems': 'Technology',
    'Monster Beverage': 'Retail',
    'Moody\'s Corporation': 'Finance & Insurance',
    'Morgan Stanley': 'Finance & Insurance',
    'Mosaic Company': 'Manufacturing / Industrial',
    'Motorola Solutions': 'Technology',
    'MSCI': 'Finance & Insurance',
    'Nasdaq, Inc.': 'Finance & Insurance',
    'National Oilwell Varco': 'Energy & Utilities',
    'NetApp': 'Technology',
    'Netflix': 'Entertainment & Media',
    'Newell Brands': 'Retail',
    'Newmont Corporation': 'Manufacturing / Industrial',
    'News Corp': 'Entertainment & Media',
    'NextEra Energy': 'Energy & Utilities',
    'Nielsen Holdings': 'Marketing',
    'Nike, Inc.': 'Retail',
    'NiSource': 'Energy & Utilities',
    'Noble Energy': 'Energy & Utilities',
    'Nordstrom': 'Retail',
    'Norfolk Southern Railway': 'Travel & Transport',
    'Northern Trust': 'Finance & Insurance',
    'Northrop Grumman': 'Manufacturing / Industrial',
    'NortonLifeLock': 'Technology',
    'NRG Energy': 'Energy & Utilities',
    'Nucor': 'Manufacturing / Industrial',
    'NVIDIA': 'Technology',
    'NVR, Inc.': 'Real Estate',
    'NXP Semiconductors': 'Technology',
    'Occidental Petroleum': 'Energy & Utilities',
    'Old Dominion Freight Line': 'Travel & Transport',
    'Omnicom Group': 'Marketing',
    'ON Semiconductor': 'Technology',
    'Oneok': 'Energy & Utilities',
    'Oracle Corporation': 'Technology',
    'Organon & Co.': 'Healthcare',
    'O\'Reilly Auto Parts': 'Retail',
    'Otis Worldwide': 'Manufacturing / Industrial',
    'Paccar': 'Manufacturing / Industrial',
    'Packaging Corporation of America': 'Manufacturing / Industrial',
    'Paramount Global': 'Entertainment & Media',
    'Parker Hannifin': 'Manufacturing / Industrial',
    'Paychex': 'Finance & Insurance',
    'Paycom': 'Finance & Insurance',
    'PayPal': 'Finance & Insurance',
    'Pentair': 'Manufacturing / Industrial',
    'PepsiCo': 'Retail',
    'PerkinElmer': 'Healthcare',
    'Pfizer': 'Healthcare',
    'PG&E Corporation': 'Energy & Utilities',
    'Philip Morris International': 'Retail',
    'Phillips 66': 'Energy & Utilities',
    'Pinnacle West Capital': 'Energy & Utilities',
    'Pioneer Natural Resources': 'Energy & Utilities',
    'PNC Financial Services': 'Finance & Insurance',
    'Pool Corporation': 'Retail',
    'PPG Industries': 'Manufacturing / Industrial',
    'PPL Corporation': 'Energy & Utilities',
    'Principal Financial Group': 'Finance & Insurance',
    'Procter & Gamble': 'Retail',
    'Progressive Corporation': 'Finance & Insurance',
    'Prologis': 'Real Estate',
    'Prudential Financial': 'Finance & Insurance',
    'Public Service Enterprise Group': 'Energy & Utilities',
    'PulteGroup': 'Real Estate',
    'Qorvo': 'Technology',
    'Quanta Services': 'Manufacturing / Industrial',
    'Quest Diagnostics': 'Healthcare',
    'Ray': 'Manufacturing / Industrial',
    'Raymond James Financial': 'Finance & Insurance',
    'Raytheon Technologies': 'Manufacturing / Industrial',
    'Realty Income': 'Real Estate',
    'Regency Centers': 'Real Estate',
    'Regeneron Pharmaceuticals': 'Healthcare',
    'Regions Financial': 'Finance & Insurance',
    'Republic Services': 'Energy & Utilities',
    'ResMed': 'Healthcare',
    'Robert Half': 'Finance & Insurance',
    'Rockwell Automation': 'Manufacturing / Industrial',
    'Rollins': 'Manufacturing / Industrial',
    'Roper Technologies': 'Technology',
    'Ross Stores': 'Retail',
    'Royal Caribbean Group': 'Travel & Transport',
    'RTX Corporation': 'Manufacturing / Industrial',
    'S&P Global': 'Finance & Insurance',
    'Salesforce': 'Technology',
    'SBA Communications': 'Technology',
    'Schlumberger': 'Energy & Utilities',
    'Seagate Technology': 'Technology',
    'Sealed Air': 'Manufacturing / Industrial',
    'Seattle Genetics': 'Healthcare',
    'Sempra Energy': 'Energy & Utilities',
    'ServiceNow': 'Technology',
    'Sherwin-Williams': 'Retail',
    'Signature Bank': 'Finance & Insurance',
    'Simon Property Group': 'Real Estate',
    'Skyworks Solutions': 'Technology',
    'SL Green Realty': 'Real Estate',
    'Smucker (J.M.)': 'Retail',
    'Snap-on': 'Manufacturing / Industrial',
    'SolarEdge Technologies': 'Energy & Utilities',
    'Southern Company': 'Energy & Utilities',
    'Southwest Airlines': 'Travel & Transport',
    'Stanley Black & Decker': 'Manufacturing / Industrial',
    'Starbucks': 'Retail',
    'State Street Corporation': 'Finance & Insurance',
    'Steel Dynamics': 'Manufacturing / Industrial',
    'Steris': 'Healthcare',
    'Stryker Corporation': 'Healthcare',
    'SVB Financial': 'Finance & Insurance',
    'Synchrony Financial': 'Finance & Insurance',
    'Synopsys': 'Technology',
    'Sysco': 'Retail',
    'T-Mobile US': 'Technology',
    'T. Rowe Price': 'Finance & Insurance',
    'Take-Two Interactive': 'Entertainment & Media',
    'Tapestry, Inc.': 'Retail',
    'Targa Resources': 'Energy & Utilities',
    'Target': 'Retail',
    'TE Connectivity': 'Technology',
    'Teledyne Technologies': 'Technology',
    'Teleflex': 'Healthcare',
    'Teradyne': 'Technology',
    'Tesla': 'Travel & Transport',
    'Textron': 'Manufacturing / Industrial',
    'The Hershey Company': 'Retail',
    'The Trade Desk': 'Technology',
    'Thermo Fisher Scientific': 'Healthcare',
    'TJX Companies': 'Retail',
    'Tractor Supply Company': 'Retail',
    'TransDigm Group': 'Manufacturing / Industrial',
    'Trane Technologies': 'Manufacturing / Industrial',
    'Travelers Companies': 'Finance & Insurance',
    'Trimble Inc.': 'Technology',
    'Truist Financial': 'Finance & Insurance',
    'TTEC Holdings': 'Technology',
    'Tyler Technologies': 'Technology',
    'Tyson Foods': 'Retail',
    'UDR, Inc.': 'Real Estate',
    'U.S. Bancorp': 'Finance & Insurance',
    'Ulta Beauty': 'Retail',
    'Union Pacific': 'Travel & Transport',
    'United Airlines Holdings': 'Travel & Transport',
    'United Parcel Service': 'Travel & Transport',
    'United Rentals': 'Manufacturing / Industrial',
    'UnitedHealth Group': 'Healthcare',
    'Universal Health Services': 'Healthcare',
    'Unum Group': 'Finance & Insurance',
    'Valero Energy': 'Energy & Utilities',
    'Ventas': 'Real Estate',
    'Verisign': 'Technology',
    'Verisk Analytics': 'Technology',
    'Verizon Communications': 'Technology',
    'Vertex Pharmaceuticals': 'Healthcare',
    'VF Corporation': 'Retail',
    'ViacomCBS': 'Entertainment & Media',
    'Visa Inc.': 'Finance & Insurance',
    'Vornado Realty Trust': 'Real Estate',
    'Vulcan Materials': 'Manufacturing / Industrial',
    'W. R. Berkley': 'Finance & Insurance',
    'W.W. Grainger': 'Retail',
    'Wabtec Corporation': 'Manufacturing / Industrial',
    'Walgreens Boots Alliance': 'Retail',
    'Walmart': 'Retail',
    'Waste Management': 'Energy & Utilities',
    'Waters Corporation': 'Healthcare',
    'WEC Energy Group': 'Energy & Utilities',
    'Wells Fargo': 'Finance & Insurance',
    'West Pharmaceutical Services': 'Healthcare',
    'Western Digital': 'Technology',
    'WestRock': 'Manufacturing / Industrial',
    'Weyerhaeuser': 'Manufacturing / Industrial',
    'Whirlpool Corporation': 'Retail',
    'Williams Companies': 'Energy & Utilities',
    'Willis Towers Watson': 'Finance & Insurance',
    'Wynn Resorts': 'Entertainment & Media',
    'Xcel Energy': 'Energy & Utilities',
    'Xerox Holdings': 'Technology',
    'Xilinx': 'Technology',
    'Xylem Inc.': 'Energy & Utilities',
    'Yum! Brands': 'Retail',
    'Zebra Technologies': 'Technology',
    'Zimmer Biomet': 'Healthcare',
    'Zions Bancorporation': 'Finance & Insurance',
    'Zoom Video Communications': 'Technology',
    'Zscaler': 'Technology'
}

